HTTP/1.0 405 Method Not Allowed
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html><body><h1>405 Method Not Allowed</h1>
The method received in the request-line is not supported by the target resource.
</body></html>

